apiVersion: v1 # Defines and limits the types of objects can be used
kind: Pod # Pods to run one or more closely related containers
metadata:
  name: client-pod # Name of the Pod
  labels:
    component: web # Tag to identify the pod. Key and values are arbitrary but must match the selector exactly
spec:
  containers: # Containers inside the pod beign created
    - name: client # Name of the container
      image: stephengrider/multi-worker #Image to download from duckerhub
      ports:
        - containerPort: 3000 # Port to expose the container to the kubernetes Node


# CONFIGURATION FILE TO CREATE A POD OBJECT

# A POD IS AN OBJECT WITH ALL THE CONTIANERS NEEDED TO WORK CLOSELY, FROM 1 TO X