apiVersion: v1 # Defines and limits the types of objects can be used
kind: Service # Services sets up networking in a kubernetes Cluster
metadata:
  name: client-node-port # Name of the cluster
spec:
  type: NodePort # Exposes a container to the outside world (for Dev only)
  ports:
    - port: 3050 # Port another pod inside the cluster can use to acces de pod selected
      targetPort: 3000 # Port of the container inside the pod selected
      nodePort: 31515 # Port on the host machine to access the container (always between 30000 - 32767)
  selector: # Selector to apply the configuration to a pod
    component: frontend # Key and values are arbitrary but must match the selector exactly


# CONFIGURATION FILE TO CREATE A CLUSTER WITH PODS INSIDE

# A SERVICE IS AN OBJECT TO CONNECT AND FORWARD THE REQUESTS FROM THE HOST
# TO TEH RUNNING POD CREATED USING THE DEPLOYMENT OBJECT.
# EVERY TIME YOU MAKE A CHANGE INTO THE DEPLOYMENT FILE, KUBERNETES(THE MASTER)
# DELETES THE PREVIOUS POD AND CREATE A NEW ONE WITH A DIFFERENT PORT INSIDE THE CLUSTER.
# SO YOU NEEED THIS SERVICES TO ORCHESTATE THE CONNECTIONS PROPERLY